### PR TITLE
modify not to use HAVE_TR1_UNORDERED_MAP

### PR DESCRIPTION
**Pull request by likerainsun**

### CODE REVIEW

**Comment by giuliopaci** [comment]
I am not sure as I am not in front of my computer right now, but I guess that AX_CXX_HEADER_UNORDERED_MAP is needed in configure.ac, to make this change complete.

Am I right?

**Comment by likerainsun** [comment]
Yes.
I just noticed I forgot to change configure.ac file.
I will push another pr.
Thanks

**Comment by likerainsun** [comment]
I first tried to push this commit to my fork version, but I guess I eventually want it to be included in the original repo version.

Sorry for pushing a request without any mention.

**Comment by giuliopaci** [comment]
Would you mind to reverse the order of the two commits? It is not very important, but modyfing configure.ac alone does not break previously working compilation, while modifying the other files without configure.ac breaks it on some systems.
Thus reversing the commits order will maximize the number of compiling commits in repo history.

**Comment by likerainsun** [comment]
@giuliopaci 
sorry for the inconvenience. I will change the commit order and push it again.

Thanks for the quick reply.
I guess I don't need the forked version.

**Comment by giuliopaci** [comment]
I also guess you do not need it. And contributors are very welcome. :-)

**Comment by likerainsun** [comment]
@giuliopaci 
Sorry again.
Do you know how to change the commit orders?
I have tried to change the commit orders in local repo and checked the ordered are changed by using rebase.
Then I pushed it to master

**Pull request closed without merging**
